# Site settings
title: Boe.codes
description: "Code and other things that live in a blog"
baseurl: ""
url: "https://boe.codes"
# User settings
username: boe.codes
user_title: Kyle Boe - Software Engineer
email: kyle@boe.codes
twitter_username: kbiz
github_username:  kyleboe
profile_picture_sm: /assets/img/kyle_sm.jpg
profile_picture: /assets/img/kyle.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: "/:title/"


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about

# projects in header index
projects:
  # - name: Some Project
  #   url: https://github.com/kyleboe/some-project

silly-things:
  - name: Rails.church
    url: https://github.com/kyleboe/rails-church

plugins:
  - amp-jekyll

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
